# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', args: '"--as-cran", "--ignore-vignettes"', build_args: '"--no-manual", "--no-build-vignettes"'}
          - {os: macOS-latest, r: 'release', args: '"--as-cran", "--ignore-vignettes"', build_args: '"--no-manual", "--no-build-vignettes"'}
          - {os: ubuntu-20.04, r: '3.6.3', args: '"--as-cran", "--ignore-vignettes"', build_args: '"--no-manual", "--no-build-vignettes"'}
          - {os: ubuntu-20.04, r: 'release',  args: '"--as-cran"', build_args: '"--no-manual"'}
          - {os: ubuntu-20.04, r: 'devel',  args: '"--as-cran"', build_args: '"--no-manual"'}

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      _R_CHECK_THINGS_IN_CHECK_DIR_: false
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_CRAN_INCOMING_USE_ASPELL_: false # Set to true when can figure how to install aspell on Windows
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install apt packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install ghostscript texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
            
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            phangorn=?ignore-before-r=4.1.0
          needs: |
            check

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Check package
        uses: r-lib/actions/check-r-package@v2 
        with:
          args: 'c(${{ matrix.config.args }}, ${{ matrix.config.build_args }})'
          build_args: 'c(${{ matrix.config.build_args }})'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
